apiVersion: tekton.dev/v1
kind: Task
metadata:
    name: source-git-check
spec:
    params:
        - default: ""
          description: A git branch ref to watch for new source
          name: git-branch
          type: string
        - default: ""
          description: A git tag ref to watch for new source
          name: git-tag
          type: string
        - default: ""
          description: A git commit sha to use
          name: git-commit
          type: string
        - description: The url to the git source repository. +Required
          name: git-url
          type: string
    results:
        - description: The url to the git source repository.
          name: url
          type: string
        - description: The sha to clone as configured by commit/branch/tag
          name: sha
          type: string
        - description: The sha to clone as configured by commit/branch/tag
          name: checksum
          type: string
        - description: Important result description, especially for error messages
          name: message
          type: string
    stepTemplate:
        computeResources: {}
        securityContext:
            allowPrivilegeEscalation: false
            capabilities:
                drop:
                    - ALL
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile:
                type: RuntimeDefault
    steps:
        - computeResources: {}
          image: us-east1-docker.pkg.dev/tanzucliappdev/tap-components/tap-packages@sha256:5a9d9e5588db709a4645ed966ad678a1a9edb44616f2fb8145493d8bce52ac02
          name: get-latest-commit
          script: |-
            #!/usr/bin/env sh
            set -eu
            url="$(params.git-url)"
            branch="$(params.git-branch)"
            tag="$(params.git-tag)"
            commit="$(params.git-commit)"

            if [ -z "$url" ]; then
              printf "No git-url provided. git-url must exist" | tee $(results.message.path)
              exit 1
            fi

            echo "$url" | tee $(results.url.path)

            if [ ! -z "$branch" ]; then
              sha=$(git ls-remote --heads $url $branch | awk '{print $1}')
              if [ -z "$sha" ]; then
                echo "\nerror using git-branch: $(params.git-branch)" | tee $(results.message.path)
                exit 1
              else
                echo $sha | tee $(results.sha.path)
                echo "\nsuccess using git-branch: $(params.git-branch)" | tee $(results.message.path)
              fi
            elif [ ! -z "$tag" ]; then
              sha=$(git ls-remote --tags $(params.git-url) refs/tags/$(params.git-tag) | awk '{print $1}')
              if [ -z "$sha" ]; then
                echo "error using git-tag: $(params.git-tag)\n" | tee $(results.message.path)
                exit 1
              else
                echo $sha | tee $(results.sha.path)
                echo "using git-tag: $(params.git-tag)\n" | tee $(results.message.path)
              fi
            elif [ ! -z "$commit" ]; then
              git_ls_remote_output=$(git ls-remote --refs $(params.git-url) | awk '{print $1}')
              if [ $? -ne 0 ]; then
                echo "error: inavlid $(params.git-url)"  | tee $(results.message.path)
                exit 1
              fi
              if echo "$git_ls_remote_output" | grep -q "$commit"; then
                echo "$(params.git-commit)" | tee $(results.sha.path)
                echo "using git-commit: $(params.git-commit)\n" | tee $(results.message.path)
              else
                echo "error: commit $(params.git-commit)not found in $(params.git-url)\n"  | tee $(results.message.path)
                exit 1
              fi
            else
              echo "Cannot look for source, you must provide one of git-branch, git-tag, git-commit or git-url.\n" | tee $(results.message.path)
              exit 1
            fi
