#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-cert
  namespace: #@ data.values.name
  annotations:
    tekton.dev/git-0: #@ data.values.tanzusupplychain.gitlab.repository
data:
  ca-bundle.crt: #@ data.values.tanzusupplychain.gitlab.ca_cert
type: Opaque