apiVersion: source.test.vmware.com/v1alpha1
kind: gitsource
metadata:
  name: "bad-branch"
spec:
  source:
    #! The sub path in the bundle to locate source code
    subPath: ""
    #! Use this object to retrieve source from a git repository.
    #! The tag, commit and branch fields are mutually exclusive, use only one.
    #! Required
    git:
      #! A git tag ref to watch for new source
      # tag: ""
      #! The url to the git source repository
      #! Required
      url: "https://github.com/rashedkvm/SupplyChain.git"
      #! A git branch ref to watch for new source
      branch: "bad-branch"
      #! A git commit sha to use
      # commit: ""
